form_schema: "../../usecases/smu/public/json/preUser.json"
program_le: "../../usecases/smu/public/le/program.le"
# TODO: Add schema corresponding to the impt parts of the pre-loaded profiles too, when time permits